CREATE TABLE Library_Branch (
	BranchID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	BranchName NVARCHAR(50) NOT NULL,
	[Address] NVARCHAR(50) NOT NULL
);

CREATE TABLE Book_Copies (
	BookID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	BranchID INT,
	Number_Of_Copies INT NOT NULL
);

CREATE TABLE Books (
	BookID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Title NVARCHAR(50) NOT NULL,
	PublisherName NVARCHAR(50)
);

CREATE TABLE Book_Authors (
	BookID INT,
	AuthorName NVARCHAR(50) NOT NULL
);

CREATE TABLE Borrower (
	CardNo INT NOT NULL PRIMARY KEY IDENTITY(100000,1),
	[Name] NVARCHAR(50) NOT NULL,
	[Address] NVARCHAR(50) NOT NULL,
	[Phone] NVARCHAR(50) NOT NULL
);

CREATE TABLE Book_Loans (
	BookID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	BranchID INT,
	CardNo INT,
	DateOut DATE NOT NULL,
	DateDue DATE NOT NULL
);

CREATE TABLE Publisher (
	PublisherName NVARCHAR(50) NOT NULL PRIMARY KEY,
	[Address] NVARCHAR(50) NOT NULL,
	[Phone] NVARCHAR(50) NOT NULL
);